networks:
  app:

services:
  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: api
    env_file:
      - app/.env
    depends_on:
      - postgres
    restart: always
    networks:
      app:
    ports:
      - "8080:8000"

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - app/.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      app:

volumes:
    postgres:
